version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
        - 8080:8080
  neo:
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    restart: always
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/data:/data
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes